#+TITLE: Pomo
#+AUTHOR: SqLait

*Pomo* is a lightweight and customisable TTY pomodoro timer for Linux Mac and BSD. It's written in pure bash, can track your progress and has a visually appealing TUI (take that GUI designers).

* Motive
During my internship I started to use the pomodoro technique for my work hours. The problem was is that there was not really a tool that would fit my niche.
The web versions required WiFi and overall felt overkill for what I really wanted to do, and existing CLIs did not have the features I cared about nor were customisable to change the timer in an easy manner.

Thus I recalled the age old saying:
#+BEGIN_QUOTE
If you want a product that checks all your boxes, you have to do it yourself.
#+END_QUOTE

* Installation
#+begin_src shell
git clone https://github.com/SqLait/pomodoro-cli.git
cd pomodoro-cli

# copy into a $PATH location
cp pomo ~/.local/bin
#+end_src

* Usage
#+BEGIN_SRC
pomo: a lightweight pomodoro timer in your terminal.
USAGE: pomo [TAG].. [OPTIONS]..
─────────────────────────────────────────────────────────
-t, --tag            |   Tag name for the current session.
-s, --session        |   Shows progress of provided session.
-l, --list           |   lists all known sessions.
-d, --duration       |   Change the default duration (25 minutes) to a custom value (in minutes) and m or s if you want either minutes or seconds.
-p, --pomodoros      |   Change the default value (4) of the amount of times you want to repeat the timer.
-r, --reconnect      |   Reconnect to a stopped session.
-rm, --remove        |   Remove a session from the database.
-a, --alarm          |   Audio file that will when the time has passed.
-cc, --create-config |   Creates a config file at $HOME/.config/pomo.

─────────────────────────────────────────────────────────
USAGE: pomo [TAG].. [SETTINGS]..
─────────────────────────────────────────────────────────
-ns, --no-save     |   Will not save the initialised session.
#+END_SRC

* Customisation
When you have used the =-cc= or =--create-config= command, a =config.txt= file will be created at $HOME/.config/pomo.

#+BEGIN_SRC
border_color = green
border_pause_color = cyan
border_complete_color = red
tag_color = blue
text_color = white
#+END_SRC

* Misc
** Contribution
All contributions to the project are welcome!

** Windows support ⚠
Momentarily there is no planned support for windows since I don't use it. But feel free to contribute if you feel like that is something important!
